- hosts: localhost
  connection: local
  become: yes

  vars:
    disk_warehouse_id: "PARTUUID=0001c4ef-01"
    disk_warehouse_mount: "/media/Warehouse"
    disk_almacen_id: "PARTUUID=80da3615-4f96-46cf-8a30-a650636d3b0e"
    disk_almacen_mount: "/media/Almacen"
    disk_ocz_id: "UUID=5adfa9de-044e-464b-a4da-22f2ea97033d"
    disk_ocz_mount: "/media/OCZ"
    service_subsonic_deb_url: "https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-6.1.6.deb"
    service_plex_deb_url: "https://downloads.plex.tv/plex-media-server-new/1.18.4.2171-ac2afe5f8/debian/plexmediaserver_1.18.4.2171-ac2afe5f8_amd64.deb"

  tasks:

  - name: apt install prereq packages
    apt:
      pkg:
      ## Baseline requirements
      - vim
      - openssh-server
      - git
      - zsh
      - samba

      ## Subsonic requirements
      - openjdk-8-jre

  ## Sytem configurations
  # fstab
  - name: create mount points
    file:
      state: directory
      mode: "1777"
      path: "{{ item }}"
    with_items:
      - "{{ disk_warehouse_mount }}"
      - "{{ disk_almacen_mount }}"
      - "{{ disk_ocz_mount }}"

  - name: mount and fstab
    mount:
      path: "{{ item.path }}"
      src: "{{ item.src }}"
      fstype: "{{ item.fstype }}"
      opts: "{{ item.opts }}"
      passno: 2
      state: mounted
    with_items:
      - { path: "{{ disk_warehouse_mount }}", src: "{{ disk_warehouse_id }}", fstype: "ntfs-3g", opts: "permissions,auto" }
      - { path: "{{ disk_almacen_mount }}", src: "{{ disk_almacen_id }}", fstype: "ntfs-3g", opts: "permissions,auto" }
      - { path: "{{ disk_ocz_mount }}", src: "{{ disk_ocz_id }}", fstype: "ext4", opts: "errors=remount-ro" }

  - name: stop and disable unnecessary services
    systemd:
      enabled: false
      state: stopped
      name: "{{ item }}"
    with_items:
      - bolt.service
      - cups-browsed.service
      - cups.service
      - ModemManager.service
      - whoopsie.service

  - name: configure hdparms spindown # just to save some always-on watts when server not in use
    lineinfile:
      path: /etc/hdparm.conf
      line: "spindown_time = 120" # 129*5s = 10min spindown

  
  ## Services
  # Samba
  - name: configure samba shares
    blockinfile:
      path: /etc/samba/smb.conf
      marker: "## Ansible managed block: {mark}"
      marker_begin: "BEGIN {{ item.name }}"
      marker_end: "END {{ item.name }}"
      block: |
        [{{ item.name }}]
          comment = "{{ item.name }}"
          path = "{{ item.path }}"
          read only = no
          guest ok = yes
    with_items:
      - { name: "Warehouse", path: "/media/Warehouse" }
      - { name: "Almacen", path: "/media/Almacen" }
      - { name: "Music", path: "/home/kyle/Music" } # NVME copy of music. Lowers HDD access
    register: configure_samba

  - name: reload samba
    when: configure_samba.changed
    systemd:
      name: "{{ item }}"
      state: reloaded
    with_items:
      - smbd.service
      - nmbd.service

  
  # Subsonic
  - name: get subsonic deb
    get_url:
      url: "{{ service_subsonic_deb_url }}"
      dest: /tmp/subsonic.deb

  - name: install subsonic
    apt:
      deb: /tmp/subsonic.deb
      state: present

  # Plex
  - name: get plex media server
    get_url:
      url: "{{ service_plex_deb_url }}"
      dest: /tmp/plex.deb
  
  - name: install plex
    apt:
      deb: /tmp/plex.deb
      state: present


  # Install Subsonic

  # Install Plex media server
  # Configure samba
  # 

  # Write out what needs configuring
  # go to {ip}:4040 to configure subsonic
  # go to {ip}:asdf to configure plex, etc
  